### ISSUE TITLE
Unity 2019 version can not support cwipc_unity pacakge

### ISSUE THREAD

**Issue by zhouzhouha** [cwi-dis/cwipc_unity#15]
![image](https://user-images.githubusercontent.com/49033781/209846675-563e08f6-df53-4d2e-9496-51bd034947d6.png)

**Comment by jackjansen** [comment]
Too bad. Let's set the minimum version to 2021.3.

**Comment by jackjansen** [comment]
Released cwipc_unity 0.10.0 which sets minimum Unity version to 2021.3.
