### ISSUE TITLE
Get the Right Hnad Controller and the trigger responce with the XR Interaction Toolkit

### ISSUE THREAD

**Issue by zhouzhouha** [cwi-dis/cwipc_unity#16]
I spent sometime to read the document and try to do this:
First, when I watch the point cloud, I press the trigger (should retrun a bool value true), then I go to the rating scene. And then I use the raycasting to interact with a slider to give a quality score. 
second, after the rating, I press the trigger then I go to the calibration.

The problem that I have now is:
1. I really couldn't get the trigger is pressed, actually I even couldn't the right controller device. (With XRI tookit)
2. In My project, the XR UI Input Module doren't include the "Input Syteme UI input module ", so I am not sure if I can still use XRI toolkit to interact with the slider.
![image](https://user-images.githubusercontent.com/49033781/209948274-49a566e4-af3d-4d86-aa08-f5cabbfac3b0.png)
I figure out how the controller is moving, its actually by touch the main button instead of press the trigger. But it has no teleport function now.

**Comment by zhouzhouha** [comment]
I managed to get the trigger value with XRI toolkit now!

**Comment by jackjansen** [comment]
My suggestion is that you don't use the trigger and grip buttons for things like "stop scene", but one of the little top buttons on the controller (I think they're called "primary button" and "secondary button").

That way, you can use the XR UI stuff as-is for your scoring: if you follow one of the examples you can create an XR canvas with UI buttons and all that, and you can use the standard setup with the XR Controller and XR Ray interactor to press the buttons.

This can be made to work even in a single scene: if the use is looking at pointclouds you disable the GameObject that has the ray interactor and no ray will be visible. Then when the user has finished looking at the pointcloud and presses the A button you enable the UI and you enable the XR Ray interactor and everything should work just fine.

**Comment by jackjansen** [comment]
The intention of this issue is lost in the mist of time. Closing.
