### ISSUE TITLE
Create PointcloudPlayback prefab that does all the right things with looping and fades

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc_unity#17]
It needs a separate controller class and a separate prefab.

It should allow you to specify the number of loops, and allow you to do preloading. It needs to have `UnityEvent`s for started and finished (so you can also add an audio track to play somewhat in sync, and/or trigger actions to happen after playback.

@zhouzhouha I think this should fit your use case.

**Comment by zhouzhouha** [comment]
Okay, should we do all of these now, or just do the preloading? Cause now I already can set the number of loops. And we don't need fade. I understand most parts of what you said except for the UnityEvent. I will read something on the UnityEvent.
