### ISSUE TITLE
Experiment with XRI teleportation and such

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc_unity#6]
There is interesting references and links in https://forum.unity.com/threads/what-are-the-teleport-input-actions-for-if-the-teleportation-provider-just-uses-select-activate.1185841/

**Comment by zhouzhouha** [comment]
I feel its difficult for me to use the XR Interaction Toolkit, I even couldn't get the responce of the trigger. For example, the trigger is pressed down. And the setting has one preoblem:
Player-> active Input Hnading->Input system package new
![image](https://user-images.githubusercontent.com/49033781/209869679-340c2dc5-04df-4253-812a-b46eb610705a.png)
Then we can use IRI toolkit, but then I can't use Input Manager. 
![image](https://user-images.githubusercontent.com/49033781/209869549-207c1669-b693-4752-b5a1-430bbfc3d77c.png)
If Player-> active Input Hnading->Both?
Maybe other package like SteamVR Open VR Loader is easier to do the interaction?

**Comment by jackjansen** [comment]
I've gotten a lot done on the issue43 cwi-dis/VR2Gather#43 branch of VR2Gather. Eventually I'll port some of this stuff to cwipc_unity.

The main take-home message is that new input system and XR Interaction toolkit is really the way to go. Also, don't use the "device based" stuff in the XR Interaction toolkit but the action-based stuff. It is much more future-proof.

The bad news (from VR2Gather point of view) is that we have to change a whole lot of things around because of the legacy code, such as having teleportation being driven by the destination (together with the locomotion provider) in stead of by the teleporter (as was the case in VRTogether).

But: this shouldn't affect cwipc_unity at all.

**Comment by jackjansen** [comment]
Implemented.
